# Generated by Django 5.2 on 2025-04-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_alter_user_mentor_project_commit_user_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='project',
        ),
        migrations.AddField(
            model_name='user',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='contributors', to='authorization.project'),
        ),
    ]
