# Generated by Django 5.2 on 2025-04-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_remove_project_user_remove_user_project_user_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='project',
            new_name='projects',
        ),
    ]
